### ISSUE TITLE
你好，我想问一下，项目怎么使用呢？

### ISSUE THREAD

**Issue by itgoyo** [Clunt/livetool#2]
你好，我想问一下，项目怎么使用呢？我把extension导入chrome，应该是一个chrome的插件，但是不知道怎么使用，可不可以在md文件里写一个稍微详细点的教程呢，谢谢了。我不是很熟悉前后端的知识，所以只能冒昧的上来问问了。

我到了你的终端有npm所以自己倒弄了一下，也不知道项目是不是这样子运行的
![](http://omvbl46i3.bkt.clouddn.com/18-4-25/45304652.jpg)

![](http://omvbl46i3.bkt.clouddn.com/18-4-25/26863535.jpg)

看了一下错误代码然后安装`npm install express`之后解决了当前的错误，又出现了新的错误，这个要怎么解决呢，0基础只能搜到这么多了，我搜索项目所有包含config的字段有的是`.config`有的是`..config`，我修改让他们全部清一色之后还是没有效果。
![](http://omvbl46i3.bkt.clouddn.com/18-4-25/81871766.jpg)
最后找到文件`config.js`
![](http://omvbl46i3.bkt.clouddn.com/18-4-25/80129758.jpg)
我不确定是不是不开播所以不成功的原因，晚点回去改我的roomid然后测试一下。

**Comment by Clunt** [comment]
```shell
cd $project_dir
cp doc/config.js ./
```
