### ISSUE TITLE
弹幕点歌的问题

### ISSUE THREAD

**Issue by itgoyo** [Clunt/livetool#3]
你好，我想问问关于弹幕点歌的问题，就是我在直播间发送点歌命令之后也生成相应的列表，网页版的网易云也自动搜索到那首歌了，但是不会自动播放，请问难道每次点歌都需要自己手动去点击播放按钮么？
例如我的网页打开`http://music.163.com/?livetool#/search/m/?s=%E8%AE%B2%E7%9C%9F%E7%9A%84`

**Comment by Clunt** [comment]
第一次点一下网易云音乐的切歌按钮，之后就可以自动切歌播放了
